remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Maryam Khursheed
description: >
  I'm a results-driven iOS developer with over a decade of experience building elegant, high-performance iOS applications. With expertise in SwiftUI and a Master's in Project Management, I bring both technical and strategic strengths to every project.
tagline: iOS Developer | SwiftUI Expert
