remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Maryam Khursheed
description: I am an iOS developer with a strong background in building clean, user-friendly apps using Swift, UIKit, and SwiftUI. I focus on writing maintainable, efficient code and enjoy solving real-world problems through thoughtful design and implementation. While my primary strength is hands-on development, I also hold a Master’s in Project Management, which helps me work effectively within teams and align technical work with broader project goals. I am currently looking for opportunities to contribute to impactful iOS projects and continue growing with the Apple developer ecosystem.


linkedin: https://www.linkedin.com/in/maryam-khursheed-56b54a104/

