remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Maryam Khursheed
description: A results-driven iOS developer with over a decade of experience building eleganthigh-performance iOS applications. With a strong foundation in UIKit and advanced expertise in SwiftUII craft modernmaintainableand intuitive user experiences. Backed by a Master’s in Project ManagementI combine technical excellence with strategic thinking to lead mobile projects from concept to App Store. I am currently seeking opportunities where I can create impactful iOS solutions and stay at the forefront of Apple’s evolving ecosystem.
tagline: iOS Developer | SwiftUI Expert
